# Generated by Django 3.2.13 on 2022-07-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_instagram_user_id', models.IntegerField()),
                ('target_instagram_user_id', models.IntegerField()),
                ('instagram_username', models.CharField(max_length=200)),
            ],
        ),
    ]
