# Generated by Django 3.2.13 on 2022-07-02 05:40

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_post_id', models.IntegerField(blank=True, null=True)),
                ('instagram_post_media_path', jsonfield.fields.JSONField(default=list)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='posts/')),
                ('caption', models.TextField(max_length=2200)),
                ('tags', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('active_comment', models.BooleanField(default=True)),
                ('show_like_view', models.BooleanField(default=True)),
                ('media_type', models.CharField(blank=True, choices=[('1', 'Photo'), ('2', 'Video'), ('8', 'Carousel')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_comment_id', models.IntegerField(null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.post')),
            ],
        ),
    ]
