# Generated by Django 3.2.13 on 2022-06-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='instagram_comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_post_id',
            field=models.IntegerField(null=True),
        ),
    ]
