# Generated by Django 3.2.13 on 2022-06-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220611_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
