# Generated by Django 3.2.13 on 2022-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220615_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='media_file',
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, choices=[('1', 'Photo'), ('2', 'Video'), ('8', 'Carousel')], max_length=1),
        ),
    ]
