# Generated by Django 3.2.13 on 2022-06-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220616_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_image',
            field=models.ImageField(null=True, upload_to='upload/photo/'),
        ),
    ]
