# Generated by Django 3.2.13 on 2022-06-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_file_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_image',
        ),
    ]
