# Generated by Django 3.2.13 on 2022-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='instagram_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
