# Generated by Django 3.2.13 on 2022-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20220629_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram_post_media_path',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
