# Generated by Django 3.2.13 on 2022-07-02 06:10

from django.db import migrations


def create_default_value(apps, schema_editor):
    MainSetting = apps.get_model('main_setting', 'MainSetting')
    MainSetting.objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ('main_setting', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_value),
    ]
