# Generated by Django 3.2.13 on 2022-06-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220606_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
