# Generated by Django 3.2.13 on 2022-06-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220613_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
