# Generated by Django 3.2.13 on 2022-06-27 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('post', 'Post'), ('post_like', 'Post Like'), ('post_unlike', 'Post Unlike'), ('comment', 'Comment'), ('comment_delete', 'Comment Delete'), ('comment_like', 'Comment Like'), ('comment_unlike', 'Comment Unlike'), ('follow', 'Follow'), ('unfollow', 'Unfollow')], max_length=14)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
