# Generated by Django 3.2.13 on 2022-06-02 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_followers_per_hour', models.IntegerField(default=10)),
                ('number_of_followers_per_day', models.IntegerField(default=200)),
                ('number_of_unfollowers_per_day', models.IntegerField(default=70)),
                ('number_of_likes_per_hour', models.IntegerField(default=300)),
                ('number_of_likes_per_day', models.IntegerField(default=7000)),
                ('number_of_comments_per_hour', models.IntegerField(default=59)),
                ('number_of_comments_per_day', models.IntegerField(default=500)),
                ('number_of_hashtags_used_in_the_post', models.IntegerField(default=30)),
                ('number_of_caption_words', models.IntegerField(default=2200)),
                ('number_of_comment_words', models.IntegerField(default=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
