# Generated by Django 3.2.13 on 2022-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(null=True, upload_to='posts/')),
                ('caption', models.TextField(max_length=2200)),
                ('tags', models.CharField(blank=True, max_length=30)),
                ('creation_at', models.DateTimeField()),
                ('active_comment', models.BooleanField(default=True)),
                ('show_like_view', models.BooleanField(default=True)),
            ],
        ),
    ]
