# Generated by Django 3.2.13 on 2022-06-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledpost',
            old_name='creation_time',
            new_name='creation_at',
        ),
    ]
