# Generated by Django 3.2.13 on 2022-06-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_post', '0002_rename_creation_time_scheduledpost_creation_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledpost',
            old_name='image',
            new_name='media_file',
        ),
    ]
